# -*- coding: utf-8 -*-
"""queuesusingArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15KQOjDiSOLe41t95vF0jDdwuUr-tke8n
"""

import numpy as np
class queuearrays:
  def __init__ (self):
    self.elements=np.arrange(10)
  def enqueue(self, data):
    return np.append(self.elements, data)
  def dequeue(self):
    return np.delete((self.elements,1))
  def front(self):
    return self.elements[0]
  def rear(self):
    return self.elements[-1]
  def length(self):
    return len(self.elements)
  def size(self):
    return (len(self.elements<10))
  def isEmpty(self):
    return (len(self.elements)==0)

