# -*- coding: utf-8 -*-
"""queuesusingDeque.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yBhsBN3O49c083HImLxb1b7daOvtGu4k
"""

from collections import deque
class queuesxdeque:
  def _init_(self):
    self.queue=deque([7,2,4,5])
  def enqueue(self,data):
    return deque.append(self.queue,data)
  def dequeue(self):
    return deque.pop(self.queue,1)
  def rear(self):
    return self.queue[-1]
  def front(self):
    return self.queue[0]
  def enqueueleft(self):
    z=deque.appendleft(self.queue,data)
    return z
  def dequeueright(self):
    c=deque.popleft(self.queue)
    return c

q = queuesxdeque()

